name: Run UFIT tests

on:
  push:
    branches: 
      - test

jobs:

  build:

    runs-on: ubuntu:22.04

    steps:
    - uses: actions/checkout@v4
    - name: Pull latest UFIT
      run: git clone https://github.com/Valentin-Aslanyan/UFiT.git
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
