name: Run UFIT tests

on:
  push:
    branches: 
      - test

jobs:
  build:
    runs-on: ubuntu:22.04

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
      - name: Clone UFIT repository
        run: git clone https://github.com/Valentin-Aslanyan/UFiT.git
      - name: Echo hello
        run: echo "hello"
